language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository

jdk: oraclejdk8

before_install:
  # for gradle output style
  - export TERM=dumb

  # environment info
  - uname -a
  - gradle -v
  - ./gradlew -version
  - java -version

  # update
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update -qq
  - sudo apt-get -y install oracle-java8-installer

  # updated java
  - java -version

script:
  - ./gradlew domain:build --stacktrace
  - ./gradlew data:build --stacktrace
  - ./gradlew presentation:build --stacktrace
